@ECHO OFF
CLS

SET YEAR=%DATE:~6,4%
SET MONTH=%DATE:~3,2%
SET DAY=%DATE:~0,2%

IF "%MONTH%" == "01" SET MONTHNAME=January
IF "%MONTH%" == "02" SET MONTHNAME=February
IF "%MONTH%" == "03" SET MONTHNAME=March
IF "%MONTH%" == "04" SET MONTHNAME=April
IF "%MONTH%" == "05" SET MONTHNAME=May
IF "%MONTH%" == "06" SET MONTHNAME=June
IF "%MONTH%" == "07" SET MONTHNAME=July
IF "%MONTH%" == "08" SET MONTHNAME=August
IF "%MONTH%" == "09" SET MONTHNAME=September
IF "%MONTH%" == "10" SET MONTHNAME=October
IF "%MONTH%" == "11" SET MONTHNAME=November
IF "%MONTH%" == "12" SET MONTHNAME=December

SET DATESTR="%MONTHNAME% %DAY%, %YEAR%"

ECHO %DATESTR%

PAUSE
